import type { AppProps } from 'next/app';
import RootLayout from '../app/layout';
import '../app/globals.css';
import Head from 'next/head';

function MyApp({ Component, pageProps }: AppProps) {
  return (
    <>
        <Head>
            <title>Create Next App</title>
            <meta name="description" content="Generated by create next app" />
        </Head>
        <RootLayout>
            <Component {...pageProps} />
        </RootLayout>
    </>
  );
}

export default MyApp;
